-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    display_name text
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX users_pkey ON users(id int4_ops);

-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE pokemon (
    id SERIAL PRIMARY KEY,
    name text,
    image text
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX pokemon_pkey ON pokemon(id int4_ops);

-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE session (
    id SERIAL PRIMARY KEY,
    created_at timestamp without time zone DEFAULT now()
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX session_pkey ON session(id int4_ops);

-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE " game_round" (
    id integer DEFAULT nextval('" game_round_id_seq"'::regclass) PRIMARY KEY,
    session_id integer REFERENCES session(id),
    created_at timestamp without time zone DEFAULT now()
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX " game_round_pkey" ON " game_round"(id int4_ops);

-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE turn (
    id SERIAL PRIMARY KEY,
    user_id integer REFERENCES users(id),
    pokemon_id integer REFERENCES pokemon(id),
    drawing text,
    round_id integer REFERENCES " game_round"(id),
    created_at timestamp without time zone DEFAULT now()
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX turn_pkey ON turn(id int4_ops);


-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE guess (
    id SERIAL PRIMARY KEY,
    turn_id integer REFERENCES turn(id),
    user_id integer REFERENCES users(id),
    guess text
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX guess_pkey ON guess(id int4_ops);
